[theme]
primaryColor = "#8AB4F8"
backgroundColor = "#131314"
secondaryBackgroundColor = "#1E1F20"
textColor = "#E3E3E3"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

[runner]
fastReruns = true
